name: Release on Tag Push

on:
  push:
    tags:
      - 'v*' # Adjust this pattern if your tags use a different format

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Release Variables
        id: vars
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          RELEASE_NAME="smj_ulm_calender_plugin${TAG_NAME}"
          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV

      - name: Zip smj-ulm-cal folder
        run: |
          zip -r smj-ulm-cal.zip smj-ulm-cal

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ env.RELEASE_NAME }}
          body: "Release for ${GITHUB_REF##*/}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: smj_ulm_calender_plugin${TAG_NAME}
          asset_name: smj_ulm_calender_plugin${TAG_NAME}
          asset_content_type: application/zip
